#
# Copyright (C) 2026 Nexwall
# SPDX-License-Identifier: GPL-2.0-only
#

import importlib.machinery
import importlib.util
import json
import os
import pathlib
import subprocess
import tempfile
import unittest

_path = pathlib.Path(__file__).resolve().parents[1] / 'files' / 'ns-dpi-bridge'
_loader = importlib.machinery.SourceFileLoader('ns_dpi_bridge', str(_path))
_spec = importlib.util.spec_from_loader('ns_dpi_bridge', _loader)
bridge = importlib.util.module_from_spec(_spec)
_loader.exec_module(bridge)

# the criteria generated by dpi-config
GENERATED = ("(iface_nfq_src == 'br-lan' or iface_nfq_dst == 'br-lan') && "
             "(local_ip == 10.0.0.5 or local_ip == 10.0.1.0/24) && "
             "(app == 'netify.netflix' or proto == 'tls' or category == 'video-streaming') ;")


def ctx(**kw):
    base = {'app': 'netify.netflix', 'app_id': 133, 'proto': 'tls', 'proto_id': 91, 'category': {'video-streaming'},
            'local_ip': '10.0.1.9', 'other_ip': '93.184.216.34', 'local_port': 51000, 'other_port': 443,
            'ip_proto': 6, 'vlan_id': 0, 'interface': 'br-lan', 'detection_guessed': False,
            'detection_complete': True}
    base.update(kw)
    return base


def event(kind='flow', **flow):
    body = {'digest': 'abc', 'local_ip': '10.0.1.9', 'other_ip': '93.184.216.34', 'local_port': 51000,
            'other_port': 443, 'ip_protocol': 6, 'ip_version': 4, 'local_bytes': 100, 'other_bytes': 900,
            'local_packets': 2, 'other_packets': 3, 'detected_application': 133,
            'detected_application_name': '133.netify.netflix', 'detected_protocol': 91,
            'detected_protocol_name': 'TLS', 'local_mac': 'aa:bb', 'local_origin': True, 'other_type': 'remote'}
    body.update(flow)
    return {'type': kind, 'interface': 'br-lan', 'internal': True, 'flow': body}


class CriteriaTest(unittest.TestCase):
    def test_generated_criteria(self):
        c = bridge.Criteria(GENERATED)
        self.assertTrue(c.matches(ctx()))
        self.assertTrue(c.matches(ctx(app='other', category=set(), local_ip='10.0.0.5')))
        self.assertFalse(c.matches(ctx(interface='eth1')))
        self.assertFalse(c.matches(ctx(local_ip='192.168.9.9')))
        self.assertFalse(c.matches(ctx(app='other', proto='dns', category=set())))

    def test_not_and_flags(self):
        c = bridge.Criteria("category == 'video-streaming' && !(proto == 'dns') && detection_complete;")
        self.assertTrue(c.matches(ctx()))
        self.assertFalse(c.matches(ctx(proto='dns')))
        self.assertTrue(bridge.Criteria('local_port >= 400 and other_port == 443').matches(ctx()))

    def test_unsupported_is_rejected(self):
        for text in ("ndpi_risk_score > 5;", "local_ip == 10.0.0.1-10.0.0.9", "app == ", "(app == 'a'", ""):
            with self.assertRaises(bridge.Unsupported, msg=text):
                bridge.Criteria(text)

    def test_ipv6(self):
        c = bridge.Criteria("local_ip == 2001:db8::/32;")
        self.assertTrue(c.matches(ctx(local_ip='2001:db8::5')))
        self.assertFalse(c.matches(ctx(local_ip='2001:dead::5')))


class CategoriesTest(unittest.TestCase):
    def load(self, data):
        with tempfile.NamedTemporaryFile('w', suffix='.json', delete=False) as f:
            json.dump(data, f)
        try:
            return bridge.load_categories(f.name)
        finally:
            os.unlink(f.name)

    def test_named_index(self):
        apps, protos = self.load({'application_index': {'video-streaming': [1, 2]}, 'protocol_index': {'web': [7]}})
        self.assertEqual(apps[1], {'video-streaming'})
        self.assertEqual(protos[7], {'web'})

    def test_tag_index(self):
        apps, _ = self.load({'application_tag_index': {'social': 10}, 'application_index': [[10, [5, 6]]]})
        self.assertEqual(apps[6], {'social'})

    def test_missing_file(self):
        self.assertEqual(bridge.load_categories('/nonexistent'), ({}, {}))


class RulesTest(unittest.TestCase):
    def ruleset(self, actions, exemptions=(), enabled=True):
        f = tempfile.NamedTemporaryFile('w', suffix='.json', delete=False)
        json.dump({'actions': actions, 'exemptions': list(exemptions)}, f)
        f.close()
        self.addCleanup(os.unlink, f.name)
        rs = bridge.RuleSet(f.name, lambda: enabled)
        rs.refresh(now=0)
        return rs

    def test_block_and_log(self):
        rs = self.ruleset({'rule0': {'enabled': True, 'criteria': GENERATED, 'targets': ['block', 'log']},
                           'analyzed': {'enabled': True, 'criteria': 'detection_guessed || detection_complete;',
                                        'targets': ['analyzed']}})
        action, matched = rs.decide(ctx())
        self.assertEqual(action, 'block')
        self.assertTrue(matched[0].log)

    def test_disabled_service(self):
        rs = self.ruleset({'rule0': {'enabled': True, 'criteria': GENERATED, 'targets': ['block']}}, enabled=False)
        self.assertEqual(rs.decide(ctx()), (None, []))

    def test_exemption(self):
        rs = self.ruleset({'rule0': {'enabled': True, 'criteria': GENERATED, 'targets': ['block']}},
                          exemptions=['10.0.1.0/24'])
        self.assertEqual(rs.decide(ctx()), (None, []))

    def test_block_beats_qos(self):
        rs = self.ruleset({'a': {'enabled': True, 'criteria': "app == 'netify.netflix';", 'targets': ['video']},
                           'b': {'enabled': True, 'criteria': "proto == 'tls';", 'targets': ['block']}})
        self.assertEqual(rs.decide(ctx())[0], 'block')

    def test_unsupported_rule_never_matches(self):
        rs = self.ruleset({'a': {'enabled': True, 'criteria': 'weird_field == 1;', 'targets': ['block']}})
        self.assertEqual(rs.decide(ctx()), (None, []))

    def test_disabled_rule(self):
        rs = self.ruleset({'a': {'enabled': False, 'criteria': "proto == 'tls';", 'targets': ['block']}})
        self.assertEqual(rs.decide(ctx()), (None, []))


class EnforcerTest(unittest.TestCase):
    def test_both_directions_and_dedupe(self):
        calls = []
        e = bridge.Enforcer(runner=calls.append, actions_log='/nonexistent/x')
        self.assertTrue(e.apply('block', ctx(), []))
        self.assertFalse(e.apply('block', ctx(), []))
        self.assertEqual(len(calls), 1)
        script = calls[0]
        self.assertIn('dpi_block4', script)
        self.assertIn('10.0.1.9 . 93.184.216.34 . tcp . 51000 . 443 timeout 1h', script)
        self.assertIn('93.184.216.34 . 10.0.1.9 . tcp . 443 . 51000 timeout 1h', script)

    def test_ipv6_and_qos_set(self):
        calls = []
        e = bridge.Enforcer(runner=calls.append)
        e.apply('voice', ctx(local_ip='2001:db8::5', other_ip='2001:db8::9', ip_proto=17), [])
        self.assertIn('dpi_voice6', calls[0])
        self.assertIn(' udp ', calls[0])

    def test_only_tcp_udp_with_ports(self):
        calls = []
        e = bridge.Enforcer(runner=calls.append)
        self.assertFalse(e.apply('block', ctx(ip_proto=1), []))
        self.assertFalse(e.apply('block', ctx(local_port=None), []))
        self.assertEqual(calls, [])

    def test_nft_failure_is_not_fatal(self):
        def boom(_):
            raise subprocess.CalledProcessError(1, 'nft', stderr='no such set')
        self.assertFalse(bridge.Enforcer(runner=boom).apply('block', ctx(), []))


class TranslationTest(unittest.TestCase):
    def test_types(self):
        self.assertEqual(bridge.to_flows_event(event('flow'))['type'], 'flow_dpi_complete')
        self.assertEqual(bridge.to_flows_event(event('flow_purge'))['type'], 'flow_purge')
        self.assertEqual(bridge.to_flows_event(event('flow_stats'))['type'], 'flow_stats')
        self.assertIsNone(bridge.to_flows_event({'type': 'agent_status'}))
        self.assertIsNone(bridge.to_flows_event({'type': 'flow'}))

    def test_fields_kept(self):
        out = bridge.to_flows_event(event('flow_purge'))
        self.assertEqual(out['interface'], 'br-lan')
        self.assertEqual(out['flow']['local_ip'], '10.0.1.9')

    def test_context_strips_app_id(self):
        c = bridge.flow_context(event(), ({133: {'video-streaming'}}, {}))
        self.assertEqual(c['app'], 'netify.netflix')
        self.assertEqual(c['category'], {'video-streaming'})


class StatsTest(unittest.TestCase):
    def test_sums_and_payload_shape(self):
        s = bridge.StatsAggregator()
        s.add(event('flow_stats'))
        s.add(event('flow_stats', digest='def'))
        s.add(event('flow_stats', local_bytes=0, other_bytes=0, other_port=80))
        payload = s.flush(now=1000)
        self.assertEqual(payload['log_time_end'], 1000)
        self.assertEqual(len(payload['stats']), 1)
        entry = payload['stats'][0]
        self.assertEqual((entry['local_bytes'], entry['other_bytes'], entry['packets']), (200, 1800, 10))
        self.assertEqual(entry['digests'], ['abc', 'def'])
        expected = {'detected_application', 'detected_application_name', 'detected_protocol',
                    'detected_protocol_name', 'digests', 'interface', 'ip_protocol', 'ip_version', 'local_bytes',
                    'local_ip', 'local_mac', 'local_origin', 'other_bytes', 'other_ip', 'other_port', 'other_type',
                    'packets'}
        self.assertEqual(set(entry), expected)
        self.assertEqual(s.flush()['stats'], [])


if __name__ == '__main__':
    unittest.main()
