##############################################################################

[sink-log]
enable = yes
plugin_library = ${path_plugin_libdir}/libnx-sink-log.so
conf_filename = ${path_state_persistent}/netify-sink-log.json

# vim: set ft=dosini :
